using BSMS.Application.Features.Common;
using BSMS.Application.Helpers;
using MediatR;

namespace BSMS.Application.Features.Route.Commands.Create;

public record CreateRouteCommand(
    string Origin,
    string Destination,
    List<CreateStops> StopsList) : IRequest<MethodResult<CreatedEntityResponse>>;

// only intermediate stops since first and last is generated by SQL trigger
public record CreateStops (
    string Name,
    int DistanceToPrevious);